### ISSUE TITLE
How can I send a mouse click?

### ISSUE THREAD

**Issue by xFatal1tYx** [2yangk23/AutoIt-Interception#1]
Hello and thank you! I love Autoit and your code helps me. Everything works great with the keyboard. But I couldn’t figure out how I can send a left mouse click, could you give me an example?  :)

**Comment by kOchirasu** [comment]
Do you need mouse click through interception? I always use normal mouse click provided by autoit. I only used interception for keypress in order to send input to directx games.

see: [MouseClick](https://www.autoitscript.com/autoit3/docs/functions/MouseClick.htm)

**Comment by xFatal1tYx** [comment]
Yes, the problem is that in my case, emulation of mouse clicks is blocked. I tried all the standard methods and WinApi methods, this does not work. Can I ask you to add a similar function for the mouse?

**Comment by kOchirasu** [comment]
Sorry, I don't have time now... very busy :(

**Comment by xFatal1tYx** [comment]
Ok, anyway thanks again )
